from __future__ import annotations

import asyncio
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.config import get_settings
from app.core.logging import get_logger
from app.db.database import DatabaseManager, init_database_manager
from app.domain.enums import (
    AvailabilityStatus,
    FulfillmentType,
    ProductCategory,
    ProviderType,
)
from app.domain.schemas import ProductCreateSchema, ProviderCreateSchema
from app.services.merchant_service import MerchantService
from app.services.product_service import ProductService
from app.services.vector_service import VectorService, get_vector_service

logger = get_logger(__name__)

SEED_PROVIDERS = [
    {
        "merchant": ProviderCreateSchema(
            name="Sharma Sweets",
            type=ProviderType.LOCAL_MERCHANT,
            description="Authentic traditional Indian sweets & snacks established in 1985.",
            location="Connaught Place, New Delhi",
            pincode="110001",
        ),
        "products": [
            ProductCreateSchema(
                name="Traditional Rasgulla",
                description="Fresh, soft, spongy cottage cheese balls soaked in chilled aromatic sugar syrup (1 kg).",
                category=ProductCategory.SWEETS,
                price_amount=45000,  # ₹450
                price_currency="INR",
                quantity=50,
                availability_status=AvailabilityStatus.IN_STOCK,
                fulfillment_type=FulfillmentType.PICKUP,
                prep_time_minutes=15,
                slot_capacity=10,
                pincode="110001",
            ),
            ProductCreateSchema(
                name="Traditional Gulab Jamun",
                description="Traditional deep-fried milk solid dumplings soaked in rose-flavored cardamom syrup (1 kg).",
                category=ProductCategory.SWEETS,
                price_amount=25000,  # ₹250
                price_currency="INR",
                quantity=30,
                availability_status=AvailabilityStatus.IN_STOCK,
                fulfillment_type=FulfillmentType.PICKUP,
                prep_time_minutes=15,
                slot_capacity=10,
                pincode="110001",
            ),
            ProductCreateSchema(
                name="Kaju Katli",
                description="Premium diamond-cut cashew fudge made with pure cashews and edible silver leaf (500g).",
                category=ProductCategory.SWEETS,
                price_amount=80000,  # ₹800
                price_currency="INR",
                quantity=25,
                availability_status=AvailabilityStatus.IN_STOCK,
                fulfillment_type=FulfillmentType.PICKUP,
                prep_time_minutes=10,
                slot_capacity=15,
                pincode="110001",
            ),
            ProductCreateSchema(
                name="Fresh Samosa",
                description="Crispy golden pastry filled with spicy potato and green peas (2 pcs).",
                category=ProductCategory.FOOD,
                price_amount=4000,  # ₹40
                price_currency="INR",
                quantity=100,
                availability_status=AvailabilityStatus.IN_STOCK,
                fulfillment_type=FulfillmentType.PICKUP,
                prep_time_minutes=5,
                slot_capacity=30,
                pincode="110001",
            ),
        ],
    },
    {
        "merchant": ProviderCreateSchema(
            name="Blinkit (CP Dark Store)",
            type=ProviderType.ENTERPRISE,
            description="Blinkit 10-minute quick-commerce fulfillment node serving central Delhi.",
            location="Connaught Place Outer Circle, Delhi",
            pincode="110001",
        ),
        "products": [
            ProductCreateSchema(
                name="Nescafe Classic Instant Coffee Powder (100g Jar)",
                description="100% pure instant coffee powder offering rich aroma and bold coffee flavor.",
                category=ProductCategory.GROCERIES,
                price_amount=29000,  # ₹290
                price_currency="INR",
                quantity=50,
                availability_status=AvailabilityStatus.IN_STOCK,
                fulfillment_type=FulfillmentType.DELIVERY,
                prep_time_minutes=10,
                slot_capacity=100,
                pincode="110001",
            ),
            ProductCreateSchema(
                name="Amul Taaza Homogenised Toned Milk (1 Litre)",
                description="Fresh pasteurised toned milk rich in calcium and protein.",
                category=ProductCategory.GROCERIES,
                price_amount=5400,  # ₹54
                price_currency="INR",
                quantity=60,
                availability_status=AvailabilityStatus.IN_STOCK,
                fulfillment_type=FulfillmentType.DELIVERY,
                prep_time_minutes=10,
                slot_capacity=100,
                pincode="110001",
            ),
            ProductCreateSchema(
                name="Haldiram Bengali Rasgulla Tin (1 kg)",
                description="Packaged Haldiram's traditional soft sponge Rasgulla Tin delivered in 10 minutes.",
                category=ProductCategory.SWEETS,
                price_amount=34000,  # ₹340
                price_currency="INR",
                quantity=40,
                availability_status=AvailabilityStatus.IN_STOCK,
                fulfillment_type=FulfillmentType.DELIVERY,
                prep_time_minutes=10,
                slot_capacity=100,
                pincode="110001",
            ),
            ProductCreateSchema(
                name="Aashirvaad Superior MP Whole Wheat Atta (1 kg)",
                description="Premium 100% pure whole wheat chakki atta flour, freshly milled for soft rotis.",
                category=ProductCategory.GROCERIES,
                price_amount=6500,  # ₹65
                price_currency="INR",
                quantity=50,
                availability_status=AvailabilityStatus.IN_STOCK,
                fulfillment_type=FulfillmentType.DELIVERY,
                prep_time_minutes=10,
                slot_capacity=100,
                pincode="110001",
            ),
            ProductCreateSchema(
                name="Fortune Sunlite Refined Sunflower Oil (1 Litre)",
                description="Refined cooking sunflower oil with essential fatty acids.",
                category=ProductCategory.GROCERIES,
                price_amount=14500,  # ₹145
                price_currency="INR",
                quantity=30,
                availability_status=AvailabilityStatus.IN_STOCK,
                fulfillment_type=FulfillmentType.DELIVERY,
                prep_time_minutes=10,
                slot_capacity=100,
                pincode="110001",
            ),
        ],
    },
    {
        "merchant": ProviderCreateSchema(
            name="Zepto (CP Hub)",
            type=ProviderType.ENTERPRISE,
            description="Zepto 8-minute delivery quick-commerce dark store node.",
            location="Barakhamba Road, Delhi",
            pincode="110001",
        ),
        "products": [
            ProductCreateSchema(
                name="Bikano Rasgulla Tin (1 kg)",
                description="Bikano Premium Rasgulla Tin with lightning-fast 8-minute delivery.",
                category=ProductCategory.SWEETS,
                price_amount=35000,  # ₹350
                price_currency="INR",
                quantity=35,
                availability_status=AvailabilityStatus.IN_STOCK,
                fulfillment_type=FulfillmentType.DELIVERY,
                prep_time_minutes=8,
                slot_capacity=100,
                pincode="110001",
            ),
            ProductCreateSchema(
                name="Nescafe Gold Premium Freeze-Dried Coffee (50g Glass Jar)",
                description="Crafted with Arabica beans for a smoother, richer taste experience.",
                category=ProductCategory.GROCERIES,
                price_amount=39000,  # ₹390
                price_currency="INR",
                quantity=20,
                availability_status=AvailabilityStatus.IN_STOCK,
                fulfillment_type=FulfillmentType.DELIVERY,
                prep_time_minutes=8,
                slot_capacity=100,
                pincode="110001",
            ),
            ProductCreateSchema(
                name="Chilled Classic Cold Coffee Can (250ml)",
                description="Ready-to-drink chilled creamy cold coffee beverage.",
                category=ProductCategory.BEVERAGES,
                price_amount=6000,  # ₹60
                price_currency="INR",
                quantity=40,
                availability_status=AvailabilityStatus.IN_STOCK,
                fulfillment_type=FulfillmentType.DELIVERY,
                prep_time_minutes=8,
                slot_capacity=100,
                pincode="110001",
            ),
            ProductCreateSchema(
                name="Aashirvaad Shudh Chakki Whole Wheat Atta Flour (1 kg)",
                description="Natural stone-ground whole wheat chakki atta flour with 8-minute delivery.",
                category=ProductCategory.GROCERIES,
                price_amount=6200,  # ₹62
                price_currency="INR",
                quantity=45,
                availability_status=AvailabilityStatus.IN_STOCK,
                fulfillment_type=FulfillmentType.DELIVERY,
                prep_time_minutes=8,
                slot_capacity=100,
                pincode="110001",
            ),
        ],
    },
    {
        "merchant": ProviderCreateSchema(
            name="Amazon India",
            type=ProviderType.MARKETPLACE,
            description="E-commerce marketplace hub offering comprehensive pantry & appliances.",
            location="New Delhi Fulfillment Center",
            pincode="110001",
        ),
        "products": [
            ProductCreateSchema(
                name="Nescafe Classic Instant Coffee Jar (200g)",
                description="Economy 200g glass jar of 100% pure instant coffee.",
                category=ProductCategory.GROCERIES,
                price_amount=58000,  # ₹580
                price_currency="INR",
                quantity=100,
                availability_status=AvailabilityStatus.IN_STOCK,
                fulfillment_type=FulfillmentType.DELIVERY,
                prep_time_minutes=1440,  # 1 day
                slot_capacity=500,
                pincode="110001",
            ),
            ProductCreateSchema(
                name="Handheld Electric Milk Frother for Cold Coffee",
                description="Battery operated stainless steel whisk frother for café style cold coffee.",
                category=ProductCategory.GENERAL,
                price_amount=29900,  # ₹299
                price_currency="INR",
                quantity=50,
                availability_status=AvailabilityStatus.IN_STOCK,
                fulfillment_type=FulfillmentType.DELIVERY,
                prep_time_minutes=1440,
                slot_capacity=500,
                pincode="110001",
            ),
        ],
    },
    {
        "merchant": ProviderCreateSchema(
            name="Apollo Pharmacy",
            type=ProviderType.LOCAL_MERCHANT,
            description="24x7 verified retail pharmacy and healthcare supply.",
            location="Janpath, New Delhi",
            pincode="110001",
        ),
        "products": [
            ProductCreateSchema(
                name="Crocin Advance 650mg (Strip of 15 Tablets)",
                description="Fast pain and fever relief paracetamol tablets.",
                category=ProductCategory.GENERAL,
                price_amount=3000,  # ₹30
                price_currency="INR",
                quantity=150,
                availability_status=AvailabilityStatus.IN_STOCK,
                fulfillment_type=FulfillmentType.PICKUP,
                prep_time_minutes=10,
                slot_capacity=50,
                pincode="110001",
            ),
            ProductCreateSchema(
                name="Electral ORS Powder (21.8g Sachet)",
                description="WHO based oral rehydration salt for instant energy and hydration.",
                category=ProductCategory.GENERAL,
                price_amount=2200,  # ₹22
                price_currency="INR",
                quantity=200,
                availability_status=AvailabilityStatus.IN_STOCK,
                fulfillment_type=FulfillmentType.PICKUP,
                prep_time_minutes=5,
                slot_capacity=50,
                pincode="110001",
            ),
        ],
    },
    {
        "merchant": ProviderCreateSchema(
            name="Old Famous Jalebi Wala",
            type=ProviderType.LOCAL_MERCHANT,
            description="Heritage sweet maker in Chandni Chowk serving pure desi ghee delicacies since 1884.",
            location="Dariba Kalan, Chandni Chowk, Delhi",
            pincode="110006",
            contact_phone="9811223344",
            contact_email="jalebiwala@chandnichowk.in",
            business_type="Sweets & Desserts",
        ),
        "products": [
            ProductCreateSchema(
                name="Desi Ghee Jalebi with Creamy Rabri (500g)",
                description="Crispy golden swirls of fermented batter fried in pure desi ghee, served with rich reduced milk rabri.",
                category=ProductCategory.SWEETS,
                price_amount=28000,
                price_currency="INR",
                quantity=40,
                availability_status=AvailabilityStatus.IN_STOCK,
                fulfillment_type=FulfillmentType.PICKUP,
                prep_time_minutes=15,
                slot_capacity=20,
                pincode="110006",
            ),
            ProductCreateSchema(
                name="Traditional Khoya Mawa Gujiya (500g)",
                description="Crisp flaky pastry stuffed with sweetened khoya, dry fruits, and aromatic cardamom.",
                category=ProductCategory.SWEETS,
                price_amount=36000,
                price_currency="INR",
                quantity=30,
                availability_status=AvailabilityStatus.IN_STOCK,
                fulfillment_type=FulfillmentType.PICKUP,
                prep_time_minutes=10,
                slot_capacity=15,
                pincode="110006",
            ),
            ProductCreateSchema(
                name="Khasta Matar Kachori with Aloo Sabzi (4 pcs)",
                description="Spiced green peas stuffed flaky kachoris served with spicy tangy Delhi style potato curry.",
                category=ProductCategory.FOOD,
                price_amount=8000,
                price_currency="INR",
                quantity=60,
                availability_status=AvailabilityStatus.IN_STOCK,
                fulfillment_type=FulfillmentType.PICKUP,
                prep_time_minutes=10,
                slot_capacity=30,
                pincode="110006",
            ),
        ],
    },
    {
        "merchant": ProviderCreateSchema(
            name="Nai Sarak Student Book & Stationery",
            type=ProviderType.LOCAL_MERCHANT,
            description="Delhi's iconic educational supplies & premium school-college stationery bookstore.",
            location="Nai Sarak, Chandni Chowk, Delhi",
            pincode="110006",
            contact_phone="9871122334",
            contact_email="naisarakbooks@gmail.com",
            business_type="Stationery & Books",
        ),
        "products": [
            ProductCreateSchema(
                name="Classmate Long Register Notebook Pack (Pack of 3, 200 Pages)",
                description="Heavyweight bright white smooth pages with durable hardbound cover for students and accounts.",
                category=ProductCategory.STATIONERY,
                price_amount=21000,
                price_currency="INR",
                quantity=80,
                availability_status=AvailabilityStatus.IN_STOCK,
                fulfillment_type=FulfillmentType.BOTH,
                prep_time_minutes=10,
                slot_capacity=40,
                pincode="110006",
            ),
            ProductCreateSchema(
                name="Reynolds 045 Fine Carbide Ball Pen Pack (10 Pens)",
                description="Classic smudge-proof smooth flowing blue ink ballpoint pens for exams and office.",
                category=ProductCategory.STATIONERY,
                price_amount=10000,
                price_currency="INR",
                quantity=120,
                availability_status=AvailabilityStatus.IN_STOCK,
                fulfillment_type=FulfillmentType.BOTH,
                prep_time_minutes=5,
                slot_capacity=60,
                pincode="110006",
            ),
            ProductCreateSchema(
                name="Camlin Kokuyo Artist Acrylic Colour Box (12 Tubes)",
                description="Rich vibrant non-toxic artist quality acrylic paint set for canvas, paper, and craft.",
                category=ProductCategory.STATIONERY,
                price_amount=27500,
                price_currency="INR",
                quantity=35,
                availability_status=AvailabilityStatus.IN_STOCK,
                fulfillment_type=FulfillmentType.BOTH,
                prep_time_minutes=10,
                slot_capacity=20,
                pincode="110006",
            ),
            ProductCreateSchema(
                name="JK Copier A4 Executive Paper Ream (75 GSM, 500 Sheets)",
                description="High-brightness multipurpose laser and inkjet printer paper ream.",
                category=ProductCategory.STATIONERY,
                price_amount=34000,
                price_currency="INR",
                quantity=50,
                availability_status=AvailabilityStatus.IN_STOCK,
                fulfillment_type=FulfillmentType.BOTH,
                prep_time_minutes=10,
                slot_capacity=25,
                pincode="110006",
            ),
        ],
    },
    {
        "merchant": ProviderCreateSchema(
            name="Roshan Di Kulfi & Sweets",
            type=ProviderType.LOCAL_MERCHANT,
            description="Legendary Karol Bagh sweet shop famed for pure milk rabri, kulfi faluda, and royal laddus.",
            location="Ajmal Khan Road, Karol Bagh, New Delhi",
            pincode="110005",
            contact_phone="9810102030",
            contact_email="roshan@kulfi.in",
            business_type="Sweets & Confectionery",
        ),
        "products": [
            ProductCreateSchema(
                name="Special Royal Faluda Kulfi Tub (500ml)",
                description="Thick rabri layered over saffron infused kulfi and chilled cornstarch vermicelli noodles.",
                category=ProductCategory.SWEETS,
                price_amount=22000,
                price_currency="INR",
                quantity=45,
                availability_status=AvailabilityStatus.IN_STOCK,
                fulfillment_type=FulfillmentType.PICKUP,
                prep_time_minutes=10,
                slot_capacity=30,
                pincode="110005",
            ),
            ProductCreateSchema(
                name="Motichoor Desi Ghee Ladoo (1 kg)",
                description="Tiny gram flour pearls fried in cow ghee and simmered in saffron cardamom syrup.",
                category=ProductCategory.SWEETS,
                price_amount=48000,
                price_currency="INR",
                quantity=40,
                availability_status=AvailabilityStatus.IN_STOCK,
                fulfillment_type=FulfillmentType.PICKUP,
                prep_time_minutes=10,
                slot_capacity=20,
                pincode="110005",
            ),
            ProductCreateSchema(
                name="Pista Kesar Rasmalai (4 pieces)",
                description="Melt-in-mouth flattened cottage cheese dumplings swimming in condensed saffron milk garnished with crushed pistachios.",
                category=ProductCategory.SWEETS,
                price_amount=24000,
                price_currency="INR",
                quantity=25,
                availability_status=AvailabilityStatus.IN_STOCK,
                fulfillment_type=FulfillmentType.PICKUP,
                prep_time_minutes=10,
                slot_capacity=15,
                pincode="110005",
            ),
        ],
    },
    {
        "merchant": ProviderCreateSchema(
            name="Vikas Stationery & Xerox Mart",
            type=ProviderType.LOCAL_MERCHANT,
            description="One-stop commercial & school stationery store in Karol Bagh market.",
            location="Arya Samaj Road, Karol Bagh, New Delhi",
            pincode="110005",
            contact_phone="9899112233",
            contact_email="vikasstationery@gmail.com",
            business_type="Stationery",
        ),
        "products": [
            ProductCreateSchema(
                name="Faber-Castell Textliner Pastel Highlighters (Set of 5)",
                description="Subtle soft pastel markers with chisel tip for textbooks, revision, and journaling.",
                category=ProductCategory.STATIONERY,
                price_amount=15000,
                price_currency="INR",
                quantity=60,
                availability_status=AvailabilityStatus.IN_STOCK,
                fulfillment_type=FulfillmentType.BOTH,
                prep_time_minutes=5,
                slot_capacity=50,
                pincode="110005",
            ),
            ProductCreateSchema(
                name="Doms Groove Triangle HB Pencils & Eraser Box (Pack of 10)",
                description="Ergonomic triangular grip pencils with dust-free eraser and precision sharpener.",
                category=ProductCategory.STATIONERY,
                price_amount=8000,
                price_currency="INR",
                quantity=100,
                availability_status=AvailabilityStatus.IN_STOCK,
                fulfillment_type=FulfillmentType.BOTH,
                prep_time_minutes=5,
                slot_capacity=50,
                pincode="110005",
            ),
            ProductCreateSchema(
                name="Kangaro Heavy Duty No. 10 Stapler Combo",
                description="Steel body stapler with built-in staple remover and 1000 rust-resistant pins.",
                category=ProductCategory.STATIONERY,
                price_amount=11000,
                price_currency="INR",
                quantity=40,
                availability_status=AvailabilityStatus.IN_STOCK,
                fulfillment_type=FulfillmentType.BOTH,
                prep_time_minutes=5,
                slot_capacity=30,
                pincode="110005",
            ),
        ],
    },
    {
        "merchant": ProviderCreateSchema(
            name="Anand Sweets & Savouries",
            type=ProviderType.LOCAL_MERCHANT,
            description="Bengaluru's premier royal sweet boutique crafting authentic South & North Indian gourmet mithai.",
            location="100 Feet Road, Indiranagar, Bengaluru",
            pincode="560038",
            contact_phone="9845012345",
            contact_email="care@anandsweets.net",
            business_type="Gourmet Sweets",
        ),
        "products": [
            ProductCreateSchema(
                name="Pure Ghee Mysore Pak Supreme (500g)",
                description="Legendary melt-in-mouth golden sweet made with roasted gram flour, cardamom, and aromatic clarified butter.",
                category=ProductCategory.SWEETS,
                price_amount=39000,
                price_currency="INR",
                quantity=50,
                availability_status=AvailabilityStatus.IN_STOCK,
                fulfillment_type=FulfillmentType.DELIVERY,
                prep_time_minutes=15,
                slot_capacity=30,
                pincode="560038",
            ),
            ProductCreateSchema(
                name="Kaju Katli Diamond Cut (500g)",
                description="Pure cashew marzipan delicacy topped with edible silver vark, made without preservatives.",
                category=ProductCategory.SWEETS,
                price_amount=65000,
                price_currency="INR",
                quantity=35,
                availability_status=AvailabilityStatus.IN_STOCK,
                fulfillment_type=FulfillmentType.DELIVERY,
                prep_time_minutes=10,
                slot_capacity=20,
                pincode="560038",
            ),
            ProductCreateSchema(
                name="Dharwad Peda Traditional (400g)",
                description="Karnataka's heritage caramelized milk sweet with rich nutty taste and granular texture.",
                category=ProductCategory.SWEETS,
                price_amount=32000,
                price_currency="INR",
                quantity=40,
                availability_status=AvailabilityStatus.IN_STOCK,
                fulfillment_type=FulfillmentType.DELIVERY,
                prep_time_minutes=10,
                slot_capacity=25,
                pincode="560038",
            ),
        ],
    },
    {
        "merchant": ProviderCreateSchema(
            name="Sapna Book House & Creative Stationery",
            type=ProviderType.LOCAL_MERCHANT,
            description="Comprehensive lifestyle stationery, fine art materials, and notebook hub in Indiranagar.",
            location="CMH Road, Indiranagar, Bengaluru",
            pincode="560038",
            contact_phone="9845198765",
            contact_email="indiranagar@sapnabooks.com",
            business_type="Books & Stationery",
        ),
        "products": [
            ProductCreateSchema(
                name="Pilot V7 Hi-Tecpoint Precision Rollerball Pens (Set of 3, Blue)",
                description="Japanese pure liquid ink rollerball pens for ultra-smooth skip-free technical writing.",
                category=ProductCategory.STATIONERY,
                price_amount=24000,
                price_currency="INR",
                quantity=50,
                availability_status=AvailabilityStatus.IN_STOCK,
                fulfillment_type=FulfillmentType.DELIVERY,
                prep_time_minutes=10,
                slot_capacity=40,
                pincode="560038",
            ),
            ProductCreateSchema(
                name="PU Leather Executive Hardcover Diary & Pen Loop (192 Pages)",
                description="Ribbon bookmark, expandable back pocket, 100 GSM acid-free bleed-proof paper.",
                category=ProductCategory.STATIONERY,
                price_amount=35000,
                price_currency="INR",
                quantity=30,
                availability_status=AvailabilityStatus.IN_STOCK,
                fulfillment_type=FulfillmentType.DELIVERY,
                prep_time_minutes=10,
                slot_capacity=20,
                pincode="560038",
            ),
            ProductCreateSchema(
                name="Scotch Magic Transparent Tape with Handheld Dispenser",
                description="Matte finish invisible tape that can be written on with pen or pencil.",
                category=ProductCategory.STATIONERY,
                price_amount=12000,
                price_currency="INR",
                quantity=60,
                availability_status=AvailabilityStatus.IN_STOCK,
                fulfillment_type=FulfillmentType.DELIVERY,
                prep_time_minutes=5,
                slot_capacity=40,
                pincode="560038",
            ),
        ],
    },
    {
        "merchant": ProviderCreateSchema(
            name="KC Das Sweets",
            type=ProviderType.LOCAL_MERCHANT,
            description="Creators of the spongy Rossogolla, serving genuine Bengali confectionary in Koramangala.",
            location="5th Block, Koramangala, Bengaluru",
            pincode="560034",
            contact_phone="9844001122",
            contact_email="kcdas.blr@gmail.com",
            business_type="Sweets",
        ),
        "products": [
            ProductCreateSchema(
                name="Authentic Spongy Rossogolla Tin (1 kg)",
                description="The original vacuum-packed spongy chhena balls in clear rose sugar syrup.",
                category=ProductCategory.SWEETS,
                price_amount=38000,
                price_currency="INR",
                quantity=40,
                availability_status=AvailabilityStatus.IN_STOCK,
                fulfillment_type=FulfillmentType.DELIVERY,
                prep_time_minutes=10,
                slot_capacity=30,
                pincode="560034",
            ),
            ProductCreateSchema(
                name="Nolen Gur Sandesh Box (8 pcs)",
                description="Winter special date palm jaggery infused chhena fudge with delicate caramel notes.",
                category=ProductCategory.SWEETS,
                price_amount=29000,
                price_currency="INR",
                quantity=25,
                availability_status=AvailabilityStatus.IN_STOCK,
                fulfillment_type=FulfillmentType.DELIVERY,
                prep_time_minutes=10,
                slot_capacity=15,
                pincode="560034",
            ),
            ProductCreateSchema(
                name="Malai Chamcham with Pistachio Shavings (500g)",
                description="Juicy oval shaped chenna sweet coated with grated mawa and silver foil.",
                category=ProductCategory.SWEETS,
                price_amount=34000,
                price_currency="INR",
                quantity=30,
                availability_status=AvailabilityStatus.IN_STOCK,
                fulfillment_type=FulfillmentType.DELIVERY,
                prep_time_minutes=10,
                slot_capacity=20,
                pincode="560034",
            ),
        ],
    },
    {
        "merchant": ProviderCreateSchema(
            name="Art & Pen Stationery Lounge",
            type=ProviderType.LOCAL_MERCHANT,
            description="Koramangala's favorite boutique for architectural sketch pads, luxury pens, and art supplies.",
            location="80 Feet Road, 7th Block, Koramangala, Bengaluru",
            pincode="560034",
            contact_phone="9844334455",
            contact_email="artpenlounge@gmail.com",
            business_type="Art & Stationery",
        ),
        "products": [
            ProductCreateSchema(
                name="Brustro Artists Cold Pressed Watercolor Paper Pad (A4, 300 GSM)",
                description="Acid-free 100% cotton cold-pressed paper suitable for watercolor, gouache, and acrylics.",
                category=ProductCategory.STATIONERY,
                price_amount=39900,
                price_currency="INR",
                quantity=30,
                availability_status=AvailabilityStatus.IN_STOCK,
                fulfillment_type=FulfillmentType.BOTH,
                prep_time_minutes=10,
                slot_capacity=20,
                pincode="560034",
            ),
            ProductCreateSchema(
                name="Staedtler Noris Triangular Graphite Sketching Pencils Set (6 Pencils)",
                description="German engineered break-resistant graphite lead for sketching, drafting, and shading.",
                category=ProductCategory.STATIONERY,
                price_amount=22000,
                price_currency="INR",
                quantity=45,
                availability_status=AvailabilityStatus.IN_STOCK,
                fulfillment_type=FulfillmentType.BOTH,
                prep_time_minutes=5,
                slot_capacity=40,
                pincode="560034",
            ),
            ProductCreateSchema(
                name="Fevicol MR Squeezy Craft Glue & Tape Combo",
                description="Non-staining synthetic adhesive bottle for school projects, craft, and paper binding.",
                category=ProductCategory.STATIONERY,
                price_amount=7500,
                price_currency="INR",
                quantity=80,
                availability_status=AvailabilityStatus.IN_STOCK,
                fulfillment_type=FulfillmentType.BOTH,
                prep_time_minutes=5,
                slot_capacity=50,
                pincode="560034",
            ),
        ],
    },
    {
        "merchant": ProviderCreateSchema(
            name="Bengali Sweet Centre",
            type=ProviderType.LOCAL_MERCHANT,
            description="South Delhi's landmark sweet and chaat destination serving authentic Mithai since 1936.",
            location="Central Market, Lajpat Nagar II, New Delhi",
            pincode="110024",
            contact_phone="9811445566",
            contact_email="bengalisweetcentre@lajpat.in",
            business_type="Sweets & Snacks",
        ),
        "products": [
            ProductCreateSchema(
                name="Kala Jamun Giant Milk Dumplings (1 kg)",
                description="Deep fried caramelized mawa balls soaked in cardamom infused heavy saffron syrup.",
                category=ProductCategory.SWEETS,
                price_amount=38000,
                price_currency="INR",
                quantity=35,
                availability_status=AvailabilityStatus.IN_STOCK,
                fulfillment_type=FulfillmentType.PICKUP,
                prep_time_minutes=15,
                slot_capacity=25,
                pincode="110024",
            ),
            ProductCreateSchema(
                name="Rajbhog Saffron Kesar Rasgulla (1 kg)",
                description="King size yellow saffron flavored cottage cheese balls stuffed with dry fruit chunks.",
                category=ProductCategory.SWEETS,
                price_amount=46000,
                price_currency="INR",
                quantity=30,
                availability_status=AvailabilityStatus.IN_STOCK,
                fulfillment_type=FulfillmentType.PICKUP,
                prep_time_minutes=15,
                slot_capacity=20,
                pincode="110024",
            ),
            ProductCreateSchema(
                name="Khaman Dhokla Sponge with Green Chutney (500g)",
                description="Steamed savory gram flour cakes tempered with mustard seeds, curry leaves, and green chillies.",
                category=ProductCategory.FOOD,
                price_amount=14000,
                price_currency="INR",
                quantity=50,
                availability_status=AvailabilityStatus.IN_STOCK,
                fulfillment_type=FulfillmentType.PICKUP,
                prep_time_minutes=10,
                slot_capacity=30,
                pincode="110024",
            ),
        ],
    },
    {
        "merchant": ProviderCreateSchema(
            name="Modern Art & Stationery Store",
            type=ProviderType.LOCAL_MERCHANT,
            description="Premium corporate and school supply retail store in South Extension.",
            location="Ring Road Market, South Extension I, New Delhi",
            pincode="110049",
            contact_phone="9811889900",
            contact_email="modernartstationery@gmail.com",
            business_type="Stationery & Office Supplies",
        ),
        "products": [
            ProductCreateSchema(
                name="Classmate Pulse Single Line A4 Spiral Notebook (300 Pages)",
                description="Micro-perforated premium white sheets with twin-wire spiral binding for college students.",
                category=ProductCategory.STATIONERY,
                price_amount=17500,
                price_currency="INR",
                quantity=70,
                availability_status=AvailabilityStatus.IN_STOCK,
                fulfillment_type=FulfillmentType.BOTH,
                prep_time_minutes=5,
                slot_capacity=40,
                pincode="110049",
            ),
            ProductCreateSchema(
                name="Parker Vector Stainless Steel Rollerball Pen (Blue Ink)",
                description="Iconic brushed stainless steel body with arrow clip and smooth tungsten carbide point.",
                category=ProductCategory.STATIONERY,
                price_amount=45000,
                price_currency="INR",
                quantity=25,
                availability_status=AvailabilityStatus.IN_STOCK,
                fulfillment_type=FulfillmentType.BOTH,
                prep_time_minutes=5,
                slot_capacity=20,
                pincode="110049",
            ),
            ProductCreateSchema(
                name="Whiteboard Dry Erase Marker Pens (Set of 4 Assorted Colors)",
                description="Low odor bold ink markers suitable for whiteboards, glass, and non-porous surfaces.",
                category=ProductCategory.STATIONERY,
                price_amount=12000,
                price_currency="INR",
                quantity=60,
                availability_status=AvailabilityStatus.IN_STOCK,
                fulfillment_type=FulfillmentType.BOTH,
                prep_time_minutes=5,
                slot_capacity=40,
                pincode="110049",
            ),
            ProductCreateSchema(
                name="Casio FX-82MS 2nd Gen Scientific Calculator (240 Functions)",
                description="Original dual-line display scientific calculator for engineering, commerce, and science students.",
                category=ProductCategory.STATIONERY,
                price_amount=54000,
                price_currency="INR",
                quantity=20,
                availability_status=AvailabilityStatus.IN_STOCK,
                fulfillment_type=FulfillmentType.BOTH,
                prep_time_minutes=5,
                slot_capacity=15,
                pincode="110049",
            ),
        ],
    },
]


async def seed_database(
    session: AsyncSession,
    vector_service: VectorService | None = None,
) -> None:
    """Seeds the database with initial merchants and products, skipping already seeded ones."""
    existing_merchants = await MerchantService.list_merchants(session)
    existing_names = {m.name.lower().strip() for m in existing_merchants}

    logger.info("Checking database seed providers...", existing_count=len(existing_merchants))
    seeded_count = 0

    for item in SEED_PROVIDERS:
        merchant_name = item["merchant"].name.strip()
        if merchant_name.lower() in existing_names:
            continue

        merchant_schema = await MerchantService.register_merchant(
            session=session,
            data=item["merchant"],
        )
        existing_names.add(merchant_name.lower())
        seeded_count += 1
        logger.info(f"Seeded merchant: {merchant_schema.name} ({merchant_schema.provider_id}) in {merchant_schema.pincode}")

        for product_data in item["products"]:
            product_schema = await ProductService.add_product(
                session=session,
                merchant_id=merchant_schema.provider_id,
                data=product_data,
                vector_service=vector_service,
            )
            logger.info(f"  -> Seeded product: {product_schema.name} at Rs {product_schema.pricing.amount / 100}")

    await session.commit()
    logger.info(f"Database seeding completed. Added {seeded_count} new merchants.")


async def main() -> None:
    """CLI runner for database seeding."""
    settings = get_settings()
    db_manager = init_database_manager(settings.DATABASE_URL)
    await db_manager.init_db()

    vector_service = get_vector_service()
    await vector_service.ensure_collection()

    async for session in db_manager.get_session():
        await seed_database(session, vector_service)
        break

    await db_manager.close()


if __name__ == "__main__":
    asyncio.run(main())
